trigger:
- main

pool:
 name: anoop5april

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'anoopkaconnection5april'
    backendAzureRmResourceGroupName: 'anoop_cicd'
    backendAzureRmStorageAccountName: 'anoopcicdstore'
    backendAzureRmContainerName: 'anoopcontainer'
    backendAzureRmKey: 'app.tfstate'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'anoopkaconnection5april'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'anoopkaconnection5april'